# Generated by Django 4.2 on 2025-05-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ikan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ikan',
        ),
    ]
