# Generated by Django 4.2 on 2025-07-03 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_produk_promo_alter_produk_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans_d',
            name='transaksi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='api.trans_h'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trans_h',
            name='kasir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kasir_transaksi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trans_h',
            name='konsumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='konsumen_transaksi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TagihanStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='menunggu', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produk')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan_supplier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
