# Generated by Django 4.2 on 2025-07-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trans_d_transaksi_alter_trans_h_kasir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembeli', models.CharField(max_length=100)),
                ('jumlah', models.PositiveIntegerField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metode_pembayaran', models.CharField(choices=[('qris', 'QRIS'), ('transfer', 'Transfer')], max_length=20)),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='bukti_transfer/')),
                ('status_pembayaran', models.CharField(choices=[('pending', 'Pending'), ('terverifikasi', 'Terverifikasi')], default='pending', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produk')),
            ],
        ),
    ]
