# Generated by Django 4.2 on 2025-05-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_ikan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField()),
            ],
        ),
    ]
