# Generated by Django 4.2 on 2025-05-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ikan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ikan',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ikan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_ikan/'),
        ),
        migrations.AddField(
            model_name='ikan',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
