# Generated by Django 4.2 on 2025-05-23 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ikan_deskripsi_ikan_gambar_ikan_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='ikan_images/'),
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('total_harga', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('tanggal_transaksi', models.DateTimeField(default=django.utils.timezone.now)),
                ('ikan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ikan')),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
