# Generated by Django 4.2 on 2025-07-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stokmasuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksishop',
            name='lokasi_pengantaran',
            field=models.TextField(blank=True, null=True),
        ),
    ]
