# Generated by Django 4.2 on 2025-05-23 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ikan_gambar_pembayaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=50, null=True)),
                ('keterangan', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='gambar_ikan/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, null=True)),
                ('tglm', models.DateField(null=True)),
                ('tgla', models.DateField(null=True)),
                ('persen', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trans_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='ikan',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='kasir',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='tanggal_transaksi',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='total_harga',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='keterangan',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='nama_pembayaran',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('kasir', 'Kasir'), ('konsumen', 'Konsumen')], default='konsumen', max_length=50),
        ),
        migrations.DeleteModel(
            name='Ikan',
        ),
        migrations.AddField(
            model_name='trans_h',
            name='Kasir',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='kasir', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trans_h',
            name='jenis_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pembayaran'),
        ),
        migrations.AddField(
            model_name='trans_h',
            name='konsumen',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='konsumen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produk',
            name='Promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.promo'),
        ),
        migrations.AddField(
            model_name='produk',
            name='ketegori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kategori'),
        ),
    ]
