# Generated by Django 4.2 on 2025-07-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaksishop_lokasi_pengantaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksishop',
            name='lokasi_pengantaran',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
